### ISSUE TITLE
Implement SEA algorithm

### ISSUE THREAD

**Issue by robinmonnier-eagleeye** [NathanRxl/concept_drift#1]
Implement SEA algorithm. It should handle data streams. 
It should have two methods:
- update(x) which updates the model whenever a new example x arrives 
- predict(x) which make a prediction for example x

**Comment by EmGarr** [comment]
Change the name of SEA.py to ensemble.py to put all the ensemble methods in it.  Put it in a package.

**Comment by EmGarr** [comment]
@g0rba I propose that we harmonise the methods from the ensemble class (like SEA). Whenever you have a new batch of features, I would have preferred to use the method fit. I allows to use non ensemble methods and ensemble approaches in frameworks like DDD.

**Comment by EmGarr** [comment]
@g0rba Could you add a method predict_proba which return the probability for each class.

**Comment by robinmonnier-eagleeye** [comment]
Yes, I will implement that later on. @EmGarr, what do you think about the name 'update' for a single exemple and 'fit' for a whole batch?

**Comment by EmGarr** [comment]
@g0rba I think it is quite the same. The algorithm should update in the same condition if it is just a single example or a batch of data. No?

**Comment by robinmonnier-eagleeye** [comment]
Hum... not really. SEA updates after a full batch has arrived. If a single example comes up, it has nothing to do except storing the example until a batch is full.

**Comment by robinmonnier-eagleeye** [comment]
Moreover, we deal with online learning, that's why our algorithms should be able to handle example by example, wich is not the case right now.

**Comment by EmGarr** [comment]
@g0rba maybe your write it not useful to use fit. Just stay with update.
