### ISSUE TITLE
Implement an SVM adaptive algorithm

### ISSUE THREAD

**Issue by NathanRxl** [NathanRxl/concept_drift#2]
Implement SVM (window) adaptive algorithm as described in http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.43.3147&rep=rep1&type=pdf.

It should handle data streams and have two methods:

update(x, y) which updates the model whenever a new labelled example (x, y) arrives
predict(x) which make a prediction for unlabelled example x

**Comment by EmGarr** [comment]
Modifications batch of different size.
