### ISSUE TITLE
Benchmarking and visualization module

### ISSUE THREAD

**Issue by NathanRxl** [NathanRxl/concept_drift#3]
We discussed with @g0rba the necessity of a particular module to handle algorithms comparison, and visualization of results.

Precise specifications are left to the assignee, but we should be able to run a script and see all the final plots for our project, on several datasets (SEA_concepts, but another one, like KDD). Parameter tuning should be easy. Final plots precise nature is still to be discussed, but for the moment, this choice is left to the assignee.

**Comment by robinmonnier-eagleeye** [comment]
For this purpose, it is important to harmonize the algorithms we implement, i.e. creating methods with the same name, same parameters, same returned objects,...

**Comment by EmGarr** [comment]
For the harmonisation I propose:
- fit method for the first training.
- update method for the training on the stream
- predict for prediction
- predict_proba returns the probability of each class (DDD needs this method when it runs ensemble learning algorithms)

- Add a method in Loader which separate training and stream data.
- Create callbacks class which would have  different purpose during the learning like register metrics to use and so on...

Maybe a class LearningExecutor would be appropriate to run the learning:

```python
class LearningExecutor:
    def __init__(self, stream_generator, learning_algo, training, callbacks):
        self.stream_generator = stream_generator
        self.clf = learning_algo
        self.X_train = training[0]
        self.y_train = training[1]
        self.callbacks = callbacks
        
    def run(self):
        self.clf.fit(self.X_train, self.y_train)
        del self.X_train
        del self.y_train
        
        for i, (X, y) in enumerate(self.stream_generator.generate(batch=1)):
            # predict
            print("predict for current X")
            y_pred = self.clf.predict(X)
            self.clf.update(X, y)
            for callback in self.callbacks:
                callback.update(y_pred)
```

**Comment by NathanRxl** [comment]
I am not against the idea of an abstraction like this.

But the stream must be unique, and not adapted to each algorithm. The algorithm must adapt to the stream, not the reverse. The comparison of the algorithms will make more sense this way, and in practice, the stream is something which is given, we cannot change its parameters.
So we do not want at the end

    LearningExecutor(stream1, algo1, **kwargs)
    LearningExecutor(stream2, algo2, **kwargs)
    ...

But more something like

    algo_comparator = AdaptiveAlgorithmsComparator()
    for i, (X, y) in enumerate(self.stream_generator.generate(batch_size=batch_size)):
       algo_comparator([algo1, algo2, algo3], (X,y))
    algo_comparator.plot_comparison()

Besides I do not think a method *fit* is needed, *update* is sufficient (the update can be different for the first batch for each algorithm if needed) see just after.

"Add a method in Loader which separate training and stream data". I think this proposition (and the previous one) comes from a misunderstanding of the problem we have: there is no original training / stream separation. You have 0 data at the beginning, a stream is coming and you begin to learn about it, trying to predict the next data coming. At the beginning, you have 0 batch in memory so your precision will be bad, that is OK. But when the number of batch you have seen increases, the algorithm must be able to predict more precisely. That is very important we all agree on the problem we are addressing. 

predict_proba is interesting, I will add it to AdaptiveSVC. The class/functions to call at the end of a learning process on a batch will be the same for all, so it could be encapsulated in the comparator (not in the algorithms).

**Comment by EmGarr** [comment]
I agree with you for:
+ AdaptativeAlgorithmsComparator
+ update and fit

I disagree with the training you will always train just once an online learning algorithm before let it make decision. So the training part idea was just to consider n data examples which are our data from the past before we let our algorithm process to some decision, classification...

**Comment by NathanRxl** [comment]
Oh, I see ! Do you mean a separation between "historical data" and "current batch" ?
Indeed, this could possibly be useful. I did some work around historical data management in AdaptiveSVC but it was fully designed for this algorithm. Perhaps it could be extracted and reused at a more abstract level.

**Comment by NathanRxl** [comment]
But we have to be sure of the great benefit of it, because it will possibly take a significant amount of time to implement it properly and we do not have any plot to discuss on the report due on next Tuesday for now.

**Comment by robinmonnier-eagleeye** [comment]
Plots are still to be defined, as metrics we want to consider besides accuracy (f1-score, recall, precision, confusion matrices,...).

@EmGarr please add to StreamGenerator a method "get_historical_data()" returning the historical data
