### ISSUE TITLE
Adaptive online algorithms internal_batch_size attribute

### ISSUE THREAD

**Issue by NathanRxl** [NathanRxl/concept_drift#5]
To obtain nice comparison plots, the size of stream generator batches will be fixed, as the batch size is directly related to the number of points in the plot.

So each algorithm must be able to work fine with a short size of batch as input. What I suggest is to design an *internal_batch_size* parameter for each algorithm which will be optimized for each algorithm.

For example:

pseudocode:
    
    ddd_clf = DDD(*ddd_args, **ddd_kwargs, internal_batch_size=50)
    dwp_clf = DWP(*dwp_args, **dwp_kwargs, internal_batch_size=200)
    sea_clf = SEA(*sea_args, **sea_kwargs, internal_batch_size=500)
    asvc_clf = AdaptiveSVC(*asvc_args, **asvc_kwargs, internal_batch_size=2000)
    for batch in StreamGenerator(batch_size=10):
        ddd_clf.update(batch)
        dwp_clf.update(batch)
        sea_clf.update(batch)
        asvc_clf.update(batch)

**Comment by EmGarr** [comment]
I agree with you.  DDD doesn't need it.
