### ISSUE TITLE
Wrapper on scikit-learn algorithms

### ISSUE THREAD

**Issue by robinmonnier-eagleeye** [NathanRxl/concept_drift#7]
In order to compare the performances between adaptive algorithms and classic one (from scikit-learn package), it is necessary to implement a wrapper which mimics the behavior of our algorithms (update() and predict() method) to plug it into AlgorithmsComparator.

As discussed with @NathanRxl, offline algorithms should fit on historical data and then never been updated.

**Comment by EmGarr** [comment]
I agree. That is what I thought.

**Comment by NathanRxl** [comment]
f292a18b45357c0e66558606637a07843ef45bed
